---
- name: Are you sure?
  pause: prompt='This operation will overwrite build.yml and destroy host_vars! Press return to continue. Press Ctrl+c and then "a" to abort'

- name: Destroy the host_vars directory and its contents
  file: path={{ playbook_dir }}/host_vars/ state=absent

- name: Destroy the group_vars directory and its contents
  file: path={{ playbook_dir }}/group_vars/ state=absent

- name: Destroy the easy_way.sh
  file: path={{ playbook_dir }}/easy_way.sh state=absent

- name: Make a backup copy of build.yml as build.bak
  copy: src={{ playbook_dir }}/build.yml dest={{ playbook_dir }}/build.bak
  ignore_errors: yes

- name: Destroy build.yml file in the playbook directory
  file: path={{ playbook_dir }}/build.yml state=absent

- name: Write out a new build.yml file to the playbook directory
  copy: src=build.yml dest={{ playbook_dir }}/build.yml

- name: Destroy hosts file in the playbook directory
  file: path={{ playbook_dir }}/hosts state=absent

- name: Destroy yml files in the playbook directory
  file: path={{ playbook_dir }}/{{ item }} state=absent
  with_items:
    - nuage-install.yml
    - vsd-deploy.yml
    - stat-deploy.yml
    - nserver-deploy.yml
    - util-deploy.yml
