---

- name: Delete the localtime file on {{ inventory_hostname }}
  file:
    path: /etc/localtime
    state: absent
  remote_user: root

- name: Create the localtime symlink on {{ inventory_hostname }}
  file:
    src: /usr/share/zoneinfo/US/Central
    dest: /etc/localtime
    state: link
  remote_user: root

- name: Remove old hostname servers on {{ inventory_hostname }}
  lineinfile:
    dest: /etc/hosts
    regexp: "^{{ interfaces[0].ip }}"
    state: absent
  remote_user: root

- name: Add hostname to hosts table {{ inventory_hostname }}
  lineinfile:
    dest: /etc/hosts
    line: "{{ interfaces[0].ip }}  {{ inventory_hostname }}"
  remote_user: root

- name: Remove old NTP servers on {{ inventory_hostname }}
  lineinfile:
    dest: /etc/ntp.conf
    regexp: "^server"
    state: absent
  remote_user: root

- name: Configure NTP servers on {{ inventory_hostname }}
  lineinfile:
    dest: /etc/ntp.conf
    line: "server {{ item }}"
  with_items: "{{ ntp_server }}"
  remote_user: root

- name: Stop the ntpd service if running
  service:
    name: ntpd
    state: stopped
  remote_user: root

- name: Manually sync time with ntp server
  command: ntpdate -u "{{ntp_server[0]}}"
  remote_user: root

- name: Start ntpd on {{ inventory_hostname }}
  service:
    name: ntpd
    state: started
  remote_user: root

- name: check ntp sync state
  shell: ntpstat | awk 'NR==1{print $1}'
  register: sync_status
  until: sync_status.stdout == "synchronised"
  retries: 29
  delay: 10
  remote_user: root

- name: "Install VSD software on standalone node, have seat, it would take a while..."
  command: /opt/vsd/vsd-install.sh -t s -y
  remote_user: root

